### ISSUE TITLE
Consider adding PathPiece instance?

### ISSUE THREAD

**Issue by iand675** [Porges/email-validate-hs#20]
http://hackage.haskell.org/package/path-pieces-0.2.1 is a widely used package, and this instance is useful when using the `EmailAddress` type from this package together with yesod forms.

The implementation is pretty straightforward:

``` haskell
instance PathPiece EmailAddress where
  toPathPiece = toPathPiece . decodeUtf8 . toByteString
  fromPathPiece = emailAddress . encodeUtf8
```

**Comment by Porges** [comment]
This is interesting. I intend to revisit this package tonight to clean up some outstanding issues, will take a look then.

**Comment by Porges** [comment]
I note that there's already a package of 'useful instances' at [cdepillabout/emailaddress](https://github.com/cdepillabout/emailaddress), which contains an instance for PathPiece.

**Comment by Porges** [comment]
At the moment I'll delegate to that rather than taking on more dependencies.
