### ISSUE TITLE
Allow testing with doctest-0.15

### ISSUE THREAD

**Issue by DanBurton** [Porges/email-validate-hs#31]
Current constraint is doctest < 0.15

**Comment by Porges** [comment]
Up on Hackage as 2.3.2.4. Thanks!

**Comment by Porges** [comment]
While you're here &ndash; is there a good way to keep on top of this myself? Just something like setup nightly builds which will always try the latest Hackage? I can't seem to find any good recommendations 🙂

**Comment by DanBurton** [comment]
Being part of Stackage while maintaining accurate version bounds is usually sufficient to get notified promptly when new versions of dependencies are out. Right now is a bit of an exception since Stackage is going through some disruption with the huge churn as we move the nightly builds over to ghc-8.4.1.

**Comment by Porges** [comment]
Yes, I normally get the github issues. So the manual reachout is just temporary? Anyway, I appreciate it!
