### ISSUE TITLE
Allow testing with hspec-2.5

### ISSUE THREAD

**Issue by DanBurton** [Porges/email-validate-hs#33]
Could I trouble you for another test suite bounds bump? :)

hspec-2.5.0 is out of bounds for:
- [ ] email-validate-2.3.2.4 (>=2.2.3 && < 2.5). George Pollard <porges@porg.es> @Porges. @Porges. Used by: test-suite

**Comment by Porges** [comment]
Uploaded as v2.3.2.5.
