### ISSUE TITLE
Quotes-wrapped `Show` intentional?

### ISSUE THREAD

**Issue by bitemyapp** [Porges/email-validate-hs#37]
Could well be the case that this was intentional, if it is, could you explain or add a comment?

```haskell
instance Show EmailAddress where
    show = show . toByteString

-- | Converts an email address back to a ByteString
toByteString :: EmailAddress -> ByteString
toByteString (EmailAddress l d) = BS.concat [l, BS.singleton '@', d]
```

It's possibly the case that for `show =` you intended it to be `unpack . toByteString` or similar. As it is, the instance renders email addresses wrapped in `" ... "` quotation marks. Let me know either way, happy to submit a PR if it should be amended. Example:

![screenshot from 2018-06-09 17-30-08](https://user-images.githubusercontent.com/320177/41196638-c53fd0c4-6c0a-11e8-9acc-32b23a6d4e76.png)

**Comment by Porges** [comment]
Yes, this was intentional, it was changed in [this PR](https://github.com/Porges/email-validate-hs/pull/6) ([diff](https://github.com/Porges/email-validate-hs/pull/6/files?w=1)). The main reason is that an email can contain Weird Stuff, so it seems safer to delimit it in Show.

e.g.:

    > validate "a.\"quoted section\"@example.com"
    Right "a.\"quotedsection\"@example.com"

otherwise this would be:

    Right a."quotedsection"@example.com

Is the quote-wrapped version causing you problems?

**Comment by bitemyapp** [comment]
>Is the quote-wrapped version causing you problems?

I wouldn't say so. It gave me pause when I was about to use `Show` for the wrong thing (lazy serialization) and instead I used the proper function (toByteString). This was a matter of curiosity.

Thank you as always! This library saves me some real grief :)

**Comment by Porges** [comment]
I'll add a note in the documentation to state what the expected behaviour is.
