### ISSUE TITLE
Underscore in domain is accepted

### ISSUE THREAD

**Issue by orlitzky** [Porges/email-validate-hs#5]
```
Prelude> :m + Text.Email.Validate Data.ByteString.UTF8
Prelude Text.Email.Validate Data.ByteString.UTF8> isValid $ fromString "local@exam_ple.com"
True
```

While underscores are legal in DNS, they're disallowed for hostnames. So you can't have either an 'A' or an 'MX' record for a name with an underscore in it, and thus no address with an underscore in it will be deliverable.

This is a gray area with respect to RFC5322, but I think it's best to reject them since in practice the addresses are invalid. A quote from the RFC:

> Note: A liberal syntax for the domain portion of addr-spec is
> given here.  However, the domain portion contains addressing
> information specified by and used in other protocols (e.g.,
> [RFC1034], [RFC1035], [RFC1123], [RFC5321]).  It is therefore
> incumbent upon implementations to conform to the syntax of
> addresses for the context in which they are used.

**Comment by orlitzky** [comment]
Thanks! I'll update my tests.

**Comment by Porges** [comment]
Note this is not yet published to hackage. I'm thinking that it is going to be 3.0 as it breaks compatibility with existing addresses.

**Comment by orlitzky** [comment]
Not a problem. I have a tool [email-validator](http://michael.orlitzky.com/code/email-validator.php) that uses email-validate for its syntax checks (which are a huge part of the program). I have no other reason to make a version bump, so I can wait and then update the version bounds to make sure my test suite passes.

On a related note, I also wrote a domain name parser in the meantime for [harbl](http://michael.orlitzky.com/git/?p=harbl.git) but I never finished the project. It's not dead per se, I just have other things to do... The goal is to parse DNS blacklist names which are essentially domain names. Someday, if I finish it, I can try to split out the domain name parsing into a library.
