### ISSUE TITLE
Please relax version constraint on 'template-haskell' to support ghc-8.10.1

### ISSUE THREAD

**Issue by peti** [Porges/email-validate-hs#51]
The latest GHC version compile this package just fine, except for the over-specified version constraint on `template-haskell` that prevents the build from running without `--allow-newer` etc. Would you mind editing the Cabal file on Hackage to relax that particular constraint?

**Comment by Porges** [comment]
@peti will do this tomorrow

**Comment by Porges** [comment]
Or today :)

Release in v2.3.2.13.
