### ISSUE TITLE
Allow newer QuickCheck

### ISSUE THREAD

**Issue by andreasabel** [Porges/email-validate-hs#71]
- https://github.com/commercialhaskell/stackage/issues/7391

**Comment by ysangkok** [comment]
@Porges Would it be possible to bump this library bound?

**Comment by Porges** [comment]
Will do this tomorrow, I'll probably just remove all the upper bounds because it's a bit tedious

**Comment by Porges** [comment]
Done: [v2.3.2.21](https://hackage.haskell.org/package/email-validate-2.3.2.21)
