### ISSUE TITLE
Use Text instead of ByteString, since emails can be unicode

### ISSUE THREAD

**Issue by nikita-volkov** [Porges/email-validate-hs#9]
For more info see http://en.wikipedia.org/wiki/Email_address#Internationalization

**Comment by Porges** [comment]
At the moment this isn't going to change because the parser doesn't support internationalized emails, so the ByteString type is used to indicate that the input is ASCII. This can change in future when it *does* support internationalized emails :grin: I'll put it on my TODO list.

**Comment by Porges** [comment]
Internationalized emails will be v3, since this changes the external interface significantly (from ByteString -> Text).

**Comment by Porges** [comment]
This is complete and will be part of v3.
